apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quest.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    {{- if .Values.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- end}}
spec:
  ingressClassName: alb
  rules:
    - host: quest-eks.newell.cloud
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "quest.fullname" . }}
                port:
                  number: 80
