apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quest.fullname" . }}
  labels:
    {{- include "quest.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "quest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quest.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "dycsail/quest:latest"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: SECRET_WORD
              value: "DiligentMouse-GKE"
