apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quest.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: quest-gke
    cert-manager.io/issuer: letsencrypt-staging
    networking.gke.io/v1beta1.FrontendConfig: quest
spec:
  tls:
    - secretName: web-ssl
      hosts:
        - quest2.gcp.newell.cloud
  rules:
    - host: quest2.gcp.newell.cloud
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "quest.fullname" . }}
                port:
                  number: 80
