apiVersion: v1
kind: Service
metadata:
  name: {{ include "quest.fullname" . }}
  labels:
    {{- include "quest.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "quest.selectorLabels" . | nindent 4 }}
